version: "3.8"
services:
  bot:
    build: .
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - TWITCH_ACCESS_TOKEN=${TWITCH_ACCESS_TOKEN}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    volumes:
      - ./configs:/app/configs
      - ./logs:/app/logs
    depends_on:
      - dashboard

  dashboard:
    build: .
    command: ["python", "dashboard.py"]
    ports:
      - "5000:5000"
